import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Dice Roller</h1>

        <div>
          <h3>Hi mom</h3>
        </div>
      </div>
    </>
  );
};

export default Home;
